---
- name: Upload Files | varnish
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: wcadmin
    mode: 0664
  with_items:
    - etc/default/varnish
    - etc/varnish/default.vcl
  notify: Reload Service | varnish
