---
- name: "Directory Exists | {{ varnish_runtime_root }}"
  file:
    state: directory
    path: "{{ varnish_runtime_root }}"
    owner: "{{ varnish_user }}"
    group: "{{ varnish_group }}"
    mode: 0775
  tags:
    - directory-structure
    - runtime-data
    - varnish

- name: Configure | varnish | initscript | pidfile
  replace:
    dest: /etc/init.d/varnish
    regexp: '/var/run/\$NAME.pid'
    replace: "{{ varnish_pidfile_path }}"
  tags:
    - initscript
    - runtime-data
    - pidfile
    - varnish

- name: Upload Files | varnish
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: "{{ varnish_user }}"
    group: "{{ varnish_group }}"
    mode: 0664
  with_items:
    - etc/default/varnish
    - etc/varnish/default.vcl
  notify: Reload Service | varnish
  tags:
    - varnish
