---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - varnish

- name: Service Stopped | varnish
  service:
    name: varnish
    state: stopped
  tags:
    - disruptive
