---
- name: Configure | varnish | initscript | pidfile
  replace:
    dest: /etc/init.d/varnish
    regexp: '/var/run/\$NAME.pid'
    replace: "{{ varnish_pidfile_path }}"
  tags:
    - initscript
    - runtime-data
    - pidfile
    - varnish
